apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: d0rka/users-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*"
    - image: d0rka/users-backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*"
