apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harjukallio-club-tls
spec:
  secretName: harjukallio-club
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: harjukallio.club
  dnsNames:
    - users2.harjukallio.club
