apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: backend
          image: %{ if docker_image != "" }${docker_image}%{ else }d0rka/users-backend%{ endif }
#          image: d0rka/users-backend
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: %{ if postgres_host != "" }${postgres_host}%{ else }postgresql%{ endif }
#              value: postgresql
            - name: POSTGRES_USER
              value: %{ if postgres_username != "" }${postgres_username}%{ else }postgres%{ endif }
#              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: postgresql-password
            - name: PGDATABASE_DEVELOPMENT
              value: users_development
            - name: PGDATABASE_TEST
              value: users_test
            - name: PGDATABASE_PRODUCTION
              value: users_production
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cis
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 3000
      targetPort: 3000
