apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: frontend
          image: d0rka/users-frontend
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_OKTA_CLIENTID
              value: 0oa6jw73iiZlcYvor357
            - name: REACT_APP_OKTA_ISSUER
              value: https://dev-556018.okta.com/oauth2/default
