apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: frontend
          image: d0rka/users-frontend
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_OKTA_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: oktaclientid
                  key: OKTA_CLIENTID
            - name: REACT_APP_OKTA_ISSUER
              valueFrom:
                secretKeyRef:
                  name: oktaissuer
                  key: OKTA_ISSUER
