apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-users
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate-users
          image: d0rka/users-backend:${gitsha}
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 2s
              trap "touch /tmp/pod/main-terminated" EXIT
              bundle exec rake db:migrate
          env:
            - name: POSTGRES_HOST
              value: ${postgres_host}
            - name: POSTGRES_USER
              value: ${postgres_username}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: postgresql-password
            - name: POSTGRES_DATABASE
              value: users_production
